smart assembly scaffold
projectawakening/builder-examples pull request #71
Opened 2024-12-19 10:59 UTC by rhubarbgarden

- users can build dapps using their own wallet of choice
- add world explorer
- add minimal toggle on/off contract example

![Screenshot 2024-12-19 at 10 54 37](https://github.com/user-attachments/assets/befdbcf0-1fba-47bb-adcf-3b9baac1f5df)
![Screenshot 2024-12-19 at 10 56 32](https://github.com/user-attachments/assets/68646f0e-8871-442e-a707-42bd50e2a39b)

2024-12-19 11:05 UTC, CCP-Red-Dragon commented on smart-assembly-scaffold/packages/contracts/.envsample
Would you be able to change it to .env if possible?

2024-12-19 11:27 UTC, rhubarbgarden commented on smart-assembly-scaffold/packages/contracts/.envsample
This is better left as `.envsample`. It's not best practice to check in `.env` as that frequently changes in local development. `.envsample` provides a template for what each dev's `.env` should look like without checking in their local environment.

2024-12-19 11:54 UTC, CCP-Grogu commented on smart-assembly-scaffold/packages/client/src/mud/useWorldContract.ts
> +  // console.log(client, sessionClient)
![image](https://github.com/user-attachments/assets/aa0bbc31-4a43-4890-82f3-b699e09eed76)

2024-12-19 11:55 UTC, CCP-Grogu approved these changes

2024-12-19 13:08 UTC, CCP-Red-Dragon requested changes
There seem to be runtime issues with connecting the wallet in-game + in the web browser.

2024-12-20 09:05 UTC, CCP-Red-Dragon approved these changes

2024-12-20 09:05 UTC, merged